apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: test
    version: beta
spec:
  containers:
  - name: hello-world-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']